# Generated by Django 4.1 on 2022-08-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Rank',
        ),
    ]
